### ISSUE TITLE
[Suggestion] Remaining for "Finishing Touches" Achievement

### ISSUE THREAD

**Issue by Nzxtime** [Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder#1]
If possible, it would be a nice feature to add a list which contains all still required enemies for the "Finishing Touches" achievement.

**Comment by kamintrug** [comment]
agree, i hope this feature is available:)

**Comment by Malin001** [comment]
I'm planning to add support for a few achievements (including Finishing Touches) in the next update, which will hopefully come out this weekend if I have enough free time :)

**Comment by Malin001** [comment]
Alright, it's been added now. It's in an experimental state though, so there's a good chance it will output the wrong enemies. For some reason, achievements don't work at all for me, so testing it is a bit difficult at the moment. Getting it to work is my top priority for the next update though

**Comment by Nzxtime** [comment]
Sadly I can't test it because I luckily got the achievement yesterday but thanks for the tool nonetheless

**Comment by Malin001** [comment]
Yeah it had a few mistakes in it as expected, but it should hopefully be working now. Still can't test it though lol
