### ISSUE TITLE
Cannot open save file

### ISSUE THREAD

**Issue by HandsomeWJ** [Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder#2]
It keeps saying it cannot open my save file, I have attached my save file for your reference
[HL-00-00.zip](https://github.com/Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder/files/10799816/HL-00-00.zip)

**Comment by ROYAN806** [comment]
Attaching the save file path with .sav is ok. For example, I input ".........\Hogwarts Legacy\Saved\SaveGames\ [num] \HL-00-00.sav".

**Comment by Malin001** [comment]
The database in your save file seems corrupted somehow. I'm still working on a way to fix this, but until then, I was able to find a way to manually extract the data needed from it. The output of the Legilimens with the manual fixes is attached.
[output.txt](https://github.com/Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder/files/10817047/output.txt)

**Comment by Treize0** [comment]
[HL-00-04.zip](https://github.com/Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder/files/10821156/HL-00-04.zip)
I have the same issue, none of my saves are able to be read.

**Comment by HandsomeWJ** [comment]
> The database in your save file seems corrupted somehow. I'm still working on a way to fix this, but until then, I was able to find a way to manually extract the data needed from it. The output of the Legilimens with the manual fixes is attached. [output.txt](https://github.com/Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder/files/10817047/output.txt)

Hmm, my save still works fine in game though, I used HLSE previously to edit some inventory items so it might be due to that?
Anyway thanks for the output.txt, I'll just use it for now :D

**Comment by Malin001** [comment]
Yeah you're save file worked fine in game for me as well. Not sure how the game is able to read it when SQLite can't. Only a single table in the database was affected though, so the only collectibles that might be wrong are Daedalian keys and Brazier/Moth/Statue field guide pages.
I've updated Legilimens to automatically detect which tables are corrupted, so a single corrupted table shouldn't completely break it anymore.
