### ISSUE TITLE
Suggestion: If possible, add a waypoint inside the game.

### ISSUE THREAD

**Issue by Thortok** [Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder#4]
Currently the program doesn't modify the game in any way which is fine, but if you could find a way to create a waypoint in game and have the program just do that instead of (or in addition to) the youtube videos, that would be a great spoiler-free way to gather collectibles. Even better if you just had a hotkey for 'find nearest collectible' (especially when combined with the 'currently obtainable' filter which was my other suggestion) and it'd just waypoint you to the nearest obtainable collectible or play some kind of sound if you have all currently obtainable collectibles.

**Comment by Malin001** [comment]
This is actually my eventual plan! Unfortunately, it requires more modding knowledge than I currently have, so it will be a while yet before I can implement it
