### ISSUE TITLE
I also have a 139/140 issue but no it doesnt give me the "congratulations you got everything msg" 

### ISSUE THREAD

**Issue by boonchu88** [Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder#6]
well at first it says im only missing a #19 moth painting in hogwarts... but im also missing a conjuration too
so i finished the number #19 and used the program at it gave me this 
https://gyazo.com/7e8f1ba915243bc2127f9960e355df9d

**Comment by Malin001** [comment]
I'm pretty sure this is happening because you input a space before your save path. I've updated it so leading/trailing whitespaces shouldn't be a problem anymore.
