### ISSUE TITLE
Incorrect Manor Cape YouTube Link

### ISSUE THREAD

**Issue by andrew-carpenter-met** [Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder#7]
The Manor Cape YouTube link for "Collection Chest #7 (Dungeon)" is the correct video, but the incorrect timecode. It should be: `https://youtu.be/gYs24rpRPZ0&t=722`.

**Comment by jiallombardo** [comment]
Same issue, it appears that the link you generate is missing the "t" parameter in the request url, here's an example screenshot:
![image](https://user-images.githubusercontent.com/11410518/221436596-d36ac904-2728-433f-82b9-12d9fbe17283.png)

P.S. But it's just a minor tidbit, I'm super-grateful for this tool, you saved me from a huge headache with those conjurations! Thanks a million!

**Comment by Malin001** [comment]
This should be fixed in the most recent versions of Legilimens, so if anyone else gets this error, just make sure you're up-to-date.
