### ISSUE TITLE
Program's github link is incorrect

### ISSUE THREAD

**Issue by Thortok** [Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder#8]
Correct link:
https://github.com/Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder

Link found inside program
![image](https://user-images.githubusercontent.com/14281289/222146597-de6d89cf-ab4f-4bea-a7b9-39033d17cc75.png)

**Comment by Malin001** [comment]
Good catch! It should actually be https://github.com/Malin001/Legilimens-Hogwarts-Legacy-cpp, since the C++ and Python versions have separate GitHub pages. Either way, it's fixed now.
