### ISSUE TITLE
Program can't find the last conjuration I'm missing 

### ISSUE THREAD

**Issue by Yitzu7** [Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder#9]
At first the program told me I was missing a single objective for an anchievement I already gotten before, which was killing a certain spider. So I killed the spider and now the program tells me I have gotten everything.
I had to put my save file in a zip as it doesn't support .sav files.
[HL-00-00.zip](https://github.com/Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder/files/10865740/HL-00-00.zip)

**Comment by Malin001** [comment]
Yeah, this is a bug in the game itself :( I added feature in the newest version to detect whether this bug happened though

[This](https://www.nexusmods.com/hogwartslegacy/mods/832) mod apparently has a fix for it, although I haven't tested it myself.
